'use strict';
const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('js/tasks/original_complex_figure.js', 'utf8');
const context = { window: { PILOT_MODE: false } };
vm.createContext(context);
vm.runInContext(source, context);
const scoring = context.window.OCFScoring;
assert.strictEqual(scoring.elementCount, 8);
assert.strictEqual(scoring.maximum, 17);
const perfect = Array.from({length:8}, (_,i)=>({element_id:String(i),accuracy:true,placement:true}));
assert.strictEqual(scoring.scoreElements(perfect,true,false).total, 17);
const oneMissing = perfect.map((r,i)=>i===0?{element_id:'0',accuracy:false,placement:true}:r);
const missingScore = scoring.scoreElements(oneMissing,true,false);
assert.strictEqual(missingScore.total, 15);
assert.strictEqual(missingScore.bonus, 0);
const incomplete = scoring.scoreElements(oneMissing,false,true);
assert.strictEqual(incomplete.total, null);
assert.strictEqual(incomplete.rawTotal, 15);
assert.strictEqual(incomplete.status, 'incomplete');
console.log('Original Complex Figure scoring checks passed.');
